name: web-app CI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Continuous Integration Test
    runs-on: ubuntu-latest
    # Remove the working-directory setting completely
    env:
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: localhost
      DB_PORT: 5432
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Debug Directory Structure
        run: |
          pwd
          ls -la

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install PostgreSQL
        run: |
          sudo apt update
          sudo apt install -y postgresql postgresql-contrib
          sudo systemctl start postgresql
          sudo systemctl enable postgresql

      - name: Configure PostgreSQL
        run: |
          sudo -u postgres psql -c "CREATE DATABASE $DB_NAME;"
          sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${DB_PASSWORD}';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO postgres;"
          echo "PostgreSQL setup complete."

      - name: Configure Environment Variables
        run: |
          echo "DB_USER=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=${{ vars.DB_NAME }}" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env

      - name: Build Packages with Maven
        run: mvn -B package -DskipTests

      - name: Run Tests
        run: mvn clean test
        env:
          DB_URL: jdbc:postgresql://localhost:5432/${{ vars.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      - name: Stop PostgreSQL Service (Optional)
        if: always()
        run: sudo systemctl stop postgresql